In [1]:
!pip install numpy

In [2]:
#numpy library
# creating numpy array
import numpy as np
arr=np.array([1,2,3])
print(arr)
arr=np.array([[1,2,3],[4,5,6]])
print(arr)
arr=np.array((1,2,3))
print(arr)

[1 2 3]
[[1 2 3]
 [4 5 6]]
[1 2 3]


In [3]:
#accessing array index
import numpy as np
arr=np.array([[-1,2,0,4],
             [4,-0.5,6,0],
             [2.6,0,7,8],
             [3,-7,4,2.0]])
arr2=arr[:2,::2]
print("first 2 rows and alternate columns(0 and 2):\n", arr2)

first 2 rows and alternate columns(0 and 2):
 [[-1.  0.]
 [ 4.  6.]]


In [4]:
# Printing elements at
# specific Indices
arr3 = arr[[1, 1, 0, 3], 
                [3, 2, 1, 0]]
print ("\nElements at indices (1, 3), "
    "(1, 2), (0, 1), (3, 0):\n", arr3)


Elements at indices (1, 3), (1, 2), (0, 1), (3, 0):
 [0. 6. 2. 3.]


In [5]:
# BASIC ARRAY OPERATIONS
import numpy as np
 
# defining Array 1
a = np.array([[1, 2],
              [3, 4]])
 
# defining Array 2
b = np.array([[4, 3],
              [2, 1]])
               
# adding 1 to every element
print ("Adding 1 to every element:", a + 1)
 
# subtracting 2 from each element
print ("\nSubtracting 2 from each element:", b - 2)
 
# sum of array elements
# Performing Unary operations
print ("\nSum of all array elements: ", a.sum())
 
# Adding two arrays
# Performing Binary operations
print ("\nArray sum:\n", a + b)

Adding 1 to every element: [[2 3]
 [4 5]]

Subtracting 2 from each element: [[ 2  1]
 [ 0 -1]]

Sum of all array elements:  10

Array sum:
 [[5 5]
 [5 5]]


In [6]:
# MATH OPERATIONS ON DATA TYPE ARRAY
import numpy as np
 
# First Array
arr1 = np.array([[4, 7], [2, 6]], 
                 dtype = np.float64)
                  
# Second Array
arr2 = np.array([[3, 6], [2, 8]], 
                 dtype = np.float64) 
 
# Addition of two Arrays
Sum = np.add(arr1, arr2)
print(Sum)
 
# Addition of all Array elements
Sum1 = np.sum(arr1)
print(Sum1)
 
# Square root of Array
Sqrt = np.sqrt(arr1)
print(Sqrt)
 
# Transpose of Array
Trans_arr = arr1.T
print(Trans_arr)

[[ 7. 13.]
 [ 4. 14.]]
19.0
[[2.         2.64575131]
 [1.41421356 2.44948974]]
[[4. 2.]
 [7. 6.]]


In [7]:
# BASIC SLICING AND INDEXING
import numpy as np  
a = np.arange(20)

print("a[15] =", a[15])
print("a[-8:17:1] =", a[-8:17:1])
print("a[10:] =", a[10:])

a[15] = 15
a[-8:17:1] = [12 13 14 15 16]
a[10:] = [10 11 12 13 14 15 16 17 18 19]


In [8]:
# ADVANCED INDEXING
import numpy as np
a = np.array( [[1, 2], [3, 4], [5, 6]] )
print( a[[0, 1, 2], [0, 0, 1]] )

[1 3 6]


In [9]:
# MATRIX OPERATIONS IN NUMPY
import numpy as np

x = np.array([[1, 2], [4, 5]])
y = np.array([[7, 8], [9, 10]])

print("Addition:\n", np.add(x, y))
print("Subtraction:\n", np.subtract(x, y))
print("Division:\n", np.divide(x, y))

Addition:
 [[ 8 10]
 [13 15]]
Subtraction:
 [[-6 -6]
 [-5 -5]]
Division:
 [[0.14285714 0.25      ]
 [0.44444444 0.5       ]]


In [10]:
import numpy as np

x = np.array([[1, 2], [4, 5]])
y = np.array([[7, 8], [9, 10]])

print("Element-wise multiplication:\n", np.multiply(x, y))
print("Matrix multiplication:\n", np.dot(x, y))

Element-wise multiplication:
 [[ 7 16]
 [36 50]]
Matrix multiplication:
 [[25 28]
 [73 82]]


In [11]:
import numpy as np

x = np.array([[1, 2], [4, 5]])
y = np.array([[7, 8], [9, 10]])

print("Square root:\n", np.sqrt(x))
print("Sum of all elements:", np.sum(y))

print("Column-wise sum:", np.sum(y, axis=0))
print("Row-wise sum:", np.sum(y, axis=1))
print("Transpose:\n", x.T)

Square root:
 [[1.         1.41421356]
 [2.         2.23606798]]
Sum of all elements: 34
Column-wise sum: [16 18]
Row-wise sum: [15 19]
Transpose:
 [[1 4]
 [2 5]]


In [12]:
#numpy arithmetic operations
import numpy as np
x=np.array([1,2,3])
y=np.array([4,5,6])
print(x)
print(y)
print(x+y)
print(x-y)
print(x*y)
print(x/y)


[1 2 3]
[4 5 6]
[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


In [13]:
import numpy as np
# Creating NumPy arrays
# 1D array
a1 = np.array([1, 2, 3, 4, 5, 6, 7, 8])

# 2D array
a2 = np.array([[1, 2],
               [3, 4],
               [5, 6],
               [7, 8]])

# 3D array
a3 = np.array([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
])

print(a1)
print(a2)
print(a3)

[1 2 3 4 5 6 7 8]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [14]:
# Using NumPy functions
c1 = np.zeros((3, 3))
c2 = np.ones((5, 5))
c3 = np.arange(0, 10, 2)
print(c1)
print(c2)
print(c3)

# Array Indexing
print(a1[2])      
print(a1[-1])    
print(a2[1][0]) 
print(a2[1][1])   
print(a3[0][0][0]) 

# Array Slicing
print(a1[1:4])    
print(a2[:, 1])

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[0 2 4 6 8]
3
8
3
4
1
[2 3 4]
[2 4 6 8]


In [15]:
#checking data types
print(type(a1))
# Parameters of array
# Shape
print(a1.shape)
print(a2.shape)
print(a3.shape)

# Rank (number of dimensions)
print(a1.ndim)
print(a2.ndim)
print(a3.ndim)

<class 'numpy.ndarray'>
(8,)
(4, 2)
(2, 2, 2)
1
2
3
